### ISSUE TITLE
Libvirt not reporting all VM interfaces

### ISSUE THREAD

**Issue by diziup** [intelsdi-x/snap-plugin-collector-libvirt#49]
Snap daemon version: 0.18.0

Environment:

Hardware configuration: Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz, 32G RAM
OS: Ubuntu 16.04.1 LTS
Kernel: Linux 4.4.0-57-generic x86_64 GNU/Linux
Relevant tools: Libvirt

**What happened**:
When using snapctl get metric list we see that per VM (domain),
not all its interfaces are reported, only a single interface (macvtap).
This is relevant for the network metrics (e.g txpackets )

**What you expected to happen**:
In previous versions, namely version 8, this procedure yielded all the interfaces that vm had (3 to be exact)

**Steps to reproduce it** (as minimally and precisely as possible):

1. load plugin v10
2. apply snapctl metric list 
3. check whether per network metrics all the interfaces are reported

**Anything else do we need to know** (e.g. issue happens only occasionally):

**Comment by IzabellaRaulin** [comment]
hello @diziup, it looks like this issue was fixed by https://github.com/intelsdi-x/snap-plugin-collector-libvirt/pull/44 in version 11. I also had noticed, that there is no available release for plugin in ver 11, so I added it. 

@diziup, could you verify if your issue still occurs for the [latest relase](https://github.com/intelsdi-x/snap-plugin-collector-libvirt/releases/tag/11)?

**Comment by sandlbn** [comment]
I will close this, no response by last 16 days and patch for this issue was released.
